{...}:
{
  imports = [
    ./bootloader.nix
    ./display-manager.nix
    ./editor.nix
    ./experimental-features.nix
    ./fonts.nix
    ./i18n.nix
    ./keyd.nix
    ./keyring.nix
    ./networking.nix
    ./security.nix
    ./services.nix
    ./sound.nix
    ./timezone.nix
    ./unfree.nix
    ./user.nix
  ];
}